// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_project: dynamic(() => import("./FeaturedProject")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  stat_row: dynamic(() => import("./StatRow")),
  vertical_cards: dynamic(() => import("./VerticalCards")),
};
